apiVersion: v1
kind: Service
metadata:
  name: trunk-jenkins
  namespace: trunk-ci
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    app: trunk-jenkins
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trunk-jenkins
  namespace: trunk-ci
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trunk-jenkins
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: trunk-jenkins
    spec:
      containers:
        - name: trunk-jenkins
          image: jenkins/jenkins:lts-jdk11
          ports:
            - name: http
              containerPort: 8080
---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: trunk-jenkins
  namespace: trunk-ci
spec:
  prefix: /
  host: jenkins.trunkapi.com
  service: trunk-jenkins
#---
#apiVersion: extensions/v1beta1
#kind: Ingress
#metadata:
#  name: jenkins-ingress
#  namespace: trunk-ci
#  annotations:
#    kubernetes.io/ingress.class: "nginx"
#spec:
#  rules:
#    - http:
#        paths:
#          - path: /jenkins
#            backend:
#              serviceName: trunk-jenkins
#              servicePort: 80
